class Ox
{
public static void main (String[]args)
{
String xworkz1= "thousand of student";
System.out.println("xworkz1:" +xworkz1);
String xworkz2= "they theach java";
System.out.println("xworkz2:" +xworkz2);
String xworkz3= "they have 5 batch";
System.out.println("xworkz3:" +xworkz3);
String xworkz4= "iam student of omkar sir";
System.out.println("xworkz4:"+xworkz4);
String xworkz5= "8clock batch";
System.out.println("xworkz5:" +xworkz5);
String tshirt= "which colour";
System.out.println("tshirt:" +tshirt);
String tshirt1= "size of the tshirt";
System.out.println("tshirt1:"+tshirt1);
String tshirt2= "prize oif tshirt";
System.out.println("tshirt2:"+tshirt2);
String mobile1= "i phone10";
System.out.println("mobile1:"+mobile1);
String mobile2= "i phone11";
System.out.println("mobile2:"+mobile2);
String mobile3= "i phone12";
System.out.println("mobile3:"+mobile3);
String mobile4= "i phone13";
System.out.println("mobile4:"+mobile4);
String mobile5= "i phone14";
System.out.println("mobile5:"+mobile5);
String mobile6= "i phone15";
System.out.println("mobile6:"+mobile6);
String andriodMobile= "samsung" ;
System.out.println("andriodMobile:"+andriodMobile);
String andriodMobile1= "oppo" ;
System.out.println("andriodMobile1:"+andriodMobile1);
String andriodMobile2= "realme" ;
System.out.println("andriodMobile2:"+andriodMobile2);
String andriodMobile3= "nokia" ;
System.out.println("andriodMobile3:"+andriodMobile3);
String andriodMobile4= "1plus" ;
System.out.println("andriodMobile4:"+andriodMobile4);
String andriodMobile5= "redme";
System.out.println("andriodMobile5:"+andriodMobile5);
String andriodMobile6= "moto" ;
System.out.println("andriodMobile6:"+andriodMobile6);
String cars= "bmw" ;
System.out.println("cars:"+cars);
String cars1= "bens" ;
System.out.println("cars1:"+cars1);

String cars2= "zen" ;
System.out.println("cars2:"+cars2);

String cars3= "swift" ;
System.out.println("cars3:"+cars3);

String cars4= "inova" ;
System.out.println("cars4:"+cars4);

String cars5= "ertiga" ;
System.out.println("cars5:"+cars5);

String cars6="ttdt";
System.out.println("cars6:"+cars6);
String cars7= "bucati" ;
System.out.println("cars7:"+cars7);

String cars8= "sdf";
System.out.println("cars8:"+cars8);

String cars9= "venuh" ;
System.out.println("cars9:"+cars9);

String cars10= "creta" ;
System.out.println("cars10:"+ cars10);
System.out.println(andriodMobile3);
System.out.println(andriodMobile6);
System.out.println(andriodMobile5);
System.out.println(cars1);
System.out.println(cars2);
System.out.println(cars6);
System.out.println(cars10);
System.out.println(xworkz1);
String var1 = "football";
        String var2 = "hockey2";
        String var3 = "tenis 3";
        String var4 = "donka 4";
        String var5 = "String 5";
        String var6 = "my frnd misfa  6";
        String var7 = "String 7";
        String var8 = "String 8";
        String var9 = "String 9";
        String var10 = "soluu 10";
        String var11 = "String 11";
        String var12 = "String 12";
        String var13 = "String 13";
        String var14 = "tigar14";
        String var15 = "String 15";
        String var16 = "String 16";
        String var17 = "Slulu7";
        String var18 = "String 18";
        String var19 = "monkey19";
        String var20 = "String 20";
        String var21 = "String 21";
        String var22 = "gorilla 22";
        String var23 = "String 23";
        String var24 = "String 24";
        String var25 = "Sdogy 25";
        String var26 = "fish 26";
        String var27 = "umma";
        String var28 = "daddy";
        String var29 = "fingure 29";
        String var30 = "String 30";
        
        

        System.out.println("var1: " + var1);
        System.out.println("var2: " + var2);
System.out.println("var3: " + var3);
        System.out.println("var4: " + var4);
System.out.println("var5: " + var5);
        System.out.println("var6: " + var6);
System.out.println("var7: " + var7);
        System.out.println("var8: " + var8);
System.out.println("var9: " + var9);
        System.out.println("var10: " + var10);
System.out.println("var11: " + var11);
        System.out.println("var12: " + var12);
System.out.println("var13: " + var13);
        System.out.println("var14: " + var14);
System.out.println("var1: " + var1);
        System.out.println("var15: " + var15);
System.out.println("var16: " + var16);
        System.out.println("var17: " + var17);
System.out.println("var18: " + var18);
        System.out.println("var19: " + var19);
System.out.println("var20: " + var20);
        System.out.println("var21: " + var21);

        System.out.println("var22: " + var22);
System.out.println("var23: " + var23);
System.out.println("var24: " + var24);
        System.out.println("var25: " + var25);
System.out.println("var26: " + var26);
        System.out.println("var27: " + var27);
System.out.println("var1: " + var1);
        System.out.println("var28: " + var28);
System.out.println("var29: " + var29);
        System.out.println("var30: " + var30);


String stng1="good moring sir";
System.out.println(stng1);
String stng2="i am sachin patil";
System.out.println(stng2);
String stng3="i am basically from ";
System.out.println(stng3);
String stng4="hubli";
System.out.println(stng4);
String stng5="but currently";
System.out.println(stng5);
String stng6="staying in banglore";
System.out.println(stng6);
String stng7=" i did my graduation";
System.out.println(stng7);
String stng8="in information science and";
System.out.println(stng8);
String stng9=" engineering";
System.out.println(stng9);
String stng10="and i did intership in";
System.out.println(stng10);
String stng11="full stack java";
System.out.println(stng11);
String stng12="in dharwad";
System.out.println(stng12);
String stng13=" currently i am traine ";
System.out.println(stng13);
String stng14="xworkz in banglore";
System.out.println(stng14);
String stng15="thank you";
System.out.println(stng15);
System.out.println(stng1+stng2+stng3+stng4+stng5+stng6+stng7+stng8+stng9+stng10+stng11+stng12+stng13+stng14+stng15);

String stng16="we did our mini";
String stng17="project";
String stng18="smart chip";
String stng19="using audinio";
String stng20="and our major ";
String stng21="project is about";
String stng22=" human following";
String stng23=" trolly with";
String stng24=" billing system";
String stng25=" this project we";
String stng26="can use in";
String stng27=" hospital,mall,airport";
String stng28=" easy to use";
String stng29=" in this system ";
String stng30=" have billing system";
String stng31="automatic it will show in moile";
String stng32="total";
String stng33=" and number of iteams";
String stng34=" advantahe:";
String stng35="we need not wait in queue in mall for bill ";
String stng36=" u can pay bill my snacing";
String stng37="our team";
String stng38="abhishek";
String stng39="flint";
String stng40="sudarshan";
String stng41="me from kadur)";
String stng42=" came here to find the best job";
String stng43="so i joind the xworkz";
String stng44="becouse this will give us the training of best java course";
String stng45=" He spent the next four decades as a scientist and science administrator, mainly at ";
String stng46="the Defence Research and Development Organisation (DRDO) and Indian Space Research ";
String stng47="Organisation (ISRO) and was intimately involved in India's civilian space programme";
String stng48=" and military missile development efforts.[1] He thus came to be known as the Missile Man ";
String stng49="of India for his work on the development of ballistic missile and launch vehicle technology.[2][3][4";
String stng50="He also played a pivotal organisational, technical, and political role in";
String stng51="India's Pokhran-II nuclear tests in ";
String stng52="1998, the first since the original nuclear test by India";
String stng53="n 1974.[5]" ;
String stng54="Kalam was elected as the 11th";
String stng55="president of India in 2002 with the support of both the ruling Bharatiya Janata Party ";
String stng56="and the then-opposition Indian National Congress.";
String stng57="Widely referred to as the People's President,[6] he returned to his";
String stng58="Widely referred to as the ";
String stng59="Widely referred to as the ";
String stng60="including the Bharat Ratna, India's highest civilian honour.";
String stng61="While delivering a lecture at the Indian Institute of Management ";
String stng62="Shillong, Kalam collapsed and died from an apparent cardiac";
String stng63="arrest on 27 July 2015, aged 83.[7] Thousands, including national-level dignitaries,";
String stng64=" attended the funeral ceremony held in";
String stng65="hometown of Rameswaram,";
String stng66=" where he was buried with full state honours.[8]";
String stng67="Early life and education";
String stng68="abhishektc";
String stng69="9591868323";
String stng70="abhishektc.xworkz@gmal.com";
String stng71="4ai20ec004";
String stng72="adichunchangiri institute of technology";
String stng73="airport";
String stng74="chikkamagluru";
String stng75="thank you";
System.out.println(stng16+stng17+stng18+stng19+stng20+stng21+stng22+stng23+stng24+stng25+stng26+stng27+stng28+stng29+stng30+stng31+stng32+stng33+stng34+stng35+stng36+stng37+stng38+stng39+stng40);
System.out.println(stng41+stng42+stng43+stng44+stng45+stng46+stng47+stng48+stng49+stng50+stng51+stng52+stng53+stng54+stng55+stng56+stng57+stng58+stng59+stng60+stng61+stng62+stng63+stng64+stng65+stng66+stng67+stng68+stng68+stng69+stng70+stng71+stng72+stng73+stng74+stng75);
}
}